### ISSUE TITLE
Oracle invalid identifier when use filter

### ISSUE THREAD

**Issue by rgiaviti** [yajra/laravel-datatables-oracle#10]
Hi!

I installed the plugin and it works pretty well! Thanks! However, when I try to filter my records, I get an Oracle error: Invalid Identifier for columns.

I debugged the problem and I saw that the plugin was putting my tables prefix before column. This happens here: https://github.com/yajra/laravel-datatables-oracle/blob/master/src/yajra/Datatables/Datatables.php#L606
```php
// line removed
$column = $db_prefix . $column;
```
So, I remove the line and it worked!

I don't know if this is a bug, but I want to let you know about this problem. If you think this is not a bug and you have another solution or if I am doing something wrong, please, let me know.

**Comment by yajra** [comment]
Hi,

Thanks for the advise. It does look like a bug. Will try to update the patches later from Bllim's version to fix the issue.
