### ISSUE TITLE
EditColumn

### ISSUE THREAD

**Issue by oakshott** [yajra/laravel-datatables-oracle#11]
I am trying to edit a date column so it only displays in d/m/y format. 

$lineManagerReviews = Course::select()->where('lineManager','=',Auth::User()->id)->where('lineManagerApproved','=','unapproved');
		return Datatables::of($lineManagerReviews)
		->editColumn('startDate', function($data) {$data->startDate->format('d/m/y');})
		->make(true);

This returns a null value for startDate can you tell me where I am going wrong please.

**Comment by yajra** [comment]
you need to add a return  on your closure:
```php
->editColumn('startDate', function($data) {return $data->startDate->format('d/m/y');})
```

**Comment by oakshott** [comment]
Thank you, I knew it would be something simple.
