### ISSUE TITLE
whereHas query and error in count query

### ISSUE THREAD

**Issue by vertoo** [yajra/laravel-datatables-oracle#16]
I have table users and roles, relation many to many. Now I need in users list display all users with role, for example "admin".
Query:
```php
$users = User::select(array( 'users.id', 'users.status', 'users.first_name', 'users.last_name', 'users.email', 'users.last_seen'))
->whereHas('roles', function($q) {
    $q->where('id', '=', 'admin');
})->with('roles');
```
This query is ok when not use it for Datatables, but when I add ::of($users) then I have exception:
```
Column not found: 1054 Unknown column 'roles' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `users` where (select count(*) from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = `users`.`id` and `name` = admin) >= 1 and `roles` LIKE %1%) count_row_table)
/framework/src/Illuminate/Database/Connection.php#620
```
Query without hasMany works fine, but filters only on users table.

I use Laravel 5, newest version of Datatables library and javascript plugin. I'm new in Laravel world, maybe I do it wrong way.

**Comment by yajra** [comment]
Hi, one way to display the roles is by using this approach:

```php
        $users = User::select(array('users.id', 'users.username','users.email',DB::raw("'roles'"), 'users.confirmed', 'users.created_at'));

        return Datatables::of($users)
            ->editColumn('roles','{{ implode(", ", User::find($id)->roles()->lists(\'name\')) }}')
            ->make(true);
```

On the other hand, I haven't tried this package yet on query with `whereHas` implementation. Will also check this out it and tests if it works given the time.

**Comment by vertoo** [comment]
After my investigation,
- queries convert to raw sql before run, 
- check for relations with $this->query->getEagerLoads();`
- replace `and related_table_name LIKE ?` with empty string
- run raw sql

This is done in `count` method 
```php
private function count()
{
    $query = $this->query;

    // if its a normal query ( no union ) replace the select with static text to improve performance
    $myQuery = clone $query;
    if ( ! preg_match('/UNION/i', strtoupper($myQuery->toSql()))) {
        $myQuery->select($this->connection->Raw("'1' as row_count"));
    }
    $relations = $myQuery->getEagerLoads();
    if (count($relations) > 0) {
        $relation_tables = array_keys($relations);
        $raw_query = str_ireplace("AND `{$relation_tables[0]}` LIKE ?", '', $myQuery->toSql());

    } else {
        $raw_query = $myQuery->toSql();
    }
    return $this->connection->table($this->connection->raw('(' . $raw_query . ') count_row_table'))
        ->setBindings($myQuery->getBindings())->count();
}
```
But in method getResult() I still have a problem:
Exception `Call to undefined method Illuminate\Database\Query\Builder::toArray()`

```php
private function getResult()
{
    $relations = $this->query->getEagerLoads();
    if (count($relations) > 0) {
        $relation_tables = array_keys($relations);
        $raw_query = str_ireplace("AND `{$relation_tables[0]}` LIKE ?", '', $this->query->toSql());

    } else {
        $raw_query = $this->query->toSql();
    }
    $this->result_object = $this->connection->table( $this->connection->raw($raw_query) )->setBindings($this->query->getBindings());
    if ($this->query_type == 'eloquent') {
        $this->result_array = array_map(function ($object) {
            return (array) $object;
        }, $this->result_object->toArray());
    } else {
        $this->result_array = array_map(function ($object) {
            return (array) $object;
        }, $this->result_object);
    }
}
```
Probably something bad in run query. This is tested only for my needs with one `whereHas`, I don't have experience with Laravel or other ORM, my solution may be stupid.

**Comment by yajra** [comment]
Hi, I just tried testing this using Laravel 5 and DT1.10++ and it works well. Maybe there is something wrong in your view and js file? Would it be possible to paste your view with js here so i can further check. Thanks!

**Comment by ErvinLlojku** [comment]
@yajra i had the same issue lately and i confirm that using your query with "->select('*')" instead of "->get()" fixes it.
