### ISSUE TITLE
removeColumn doesn't remove the column from the sColumns array

### ISSUE THREAD

**Issue by Zalon** [yajra/laravel-datatables-oracle#18]
I have an issue where if i use removeColumn, the column will still be included in the sColumns array.

Using removeColumn will remove the column from the data array, but will it will still be included in the sColumns part.

The result is that when reordering, it will order by the wrong column.

Sorry for the vague explanation.

**Comment by intrepidtr** [comment]
+1 or -1 select  exxample id,name,slug  error later id,name,slug,id

**Comment by yajra** [comment]
Hi, it seems that you were using Datatables v1.9 and below. I suggest you update to version 1.10++ if possible. See #12 for a sample code reference. I do recognized that the support for lower version is a little buggy and haven't used it already.

On the other hand, will check this given the time. Thanks for reporting.

**Comment by illuminate3** [comment]
As yajra said check out issue #12 for better examples.

I was having issues on the controller side. I set the column to "visible: false" on the view side and it works.

**Comment by Zalon** [comment]
Sorry for my late reply, I'm using datatables 1.10.5

I build the datatable in the controller and use ->remove_column('id')

    public function data()
    {
        $event = Event::select(array('events.id', 'events.title', 'events.date', 'events.recurring', 'events.highlight', 'events.created_at'))
            ->orderBy('events.position', 'ASC');

        $test = Datatables::of($event)
            ->edit_column('date', '{{{ date("Y-m-d (D)", strtotime($date)) }}}')
            ->edit_column('recurring', '@if ($recurring) {{{ $recurring }}} @else off @endif')
            ->edit_column('highlight', '@if ($highlight=="1") <span class="glyphicon glyphicon-ok"></span> @else <span class=\'glyphicon glyphicon-remove\'></span> @endif')
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/event/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm iframe" ><span class="glyphicon glyphicon-pencil"></span>  {{ Lang::get("admin/modal.edit") }}</a>
                    <a href="{{{ URL::to(\'admin/event/\' . $id . \'/delete\' ) }}}" class="btn btn-sm btn-danger iframe"><span class="glyphicon glyphicon-trash"></span> {{ Lang::get("admin/modal.delete") }}</a>
                    <input type="hidden" name="row" value="{{$id}}" id="row">')
            ->remove_column('id')

            ->make();

        \Log::error($test);
        return $test;
    }

That will result in this reply, that i use in the view for the datatable

    {"sEcho":6,"iTotalRecords":5,"iTotalDisplayRecords":5,"aaData":[["abe","2015-04-08 (Wed)"," off "," <span class='glyphicon glyphicon-remove'><\/span> ","2015-04-01 03:27:07","<a href=\"http:\/\/localhost:8000\/admin\/event\/11\/edit\" class=\"btn btn-success btn-sm iframe\" ><span class=\"glyphicon glyphicon-pencil\"><\/span>  Edit<\/a>\n                    <a href=\"http:\/\/localhost:8000\/admin\/event\/11\/delete\" class=\"btn btn-sm btn-danger iframe\"><span class=\"glyphicon glyphicon-trash\"><\/span> Delete<\/a>\n                    <input type=\"hidden\" name=\"row\" value=\"11\" id=\"row\">"],["abe","2015-04-16 (Thu)"," off "," <span class='glyphicon glyphicon-remove'><\/span> ","2015-04-01 03:42:55","<a href=\"http:\/\/localhost:8000\/admin\/event\/14\/edit\" class=\"btn btn-success btn-sm iframe\" ><span class=\"glyphicon glyphicon-pencil\"><\/span>  Edit<\/a>\n                    <a href=\"http:\/\/localhost:8000\/admin\/event\/14\/delete\" class=\"btn btn-sm btn-danger iframe\"><span class=\"glyphicon glyphicon-trash\"><\/span> Delete<\/a>\n                    <input type=\"hidden\" name=\"row\" value=\"14\" id=\"row\">"],["abe","2015-04-16 (Thu)"," off "," <span class='glyphicon glyphicon-remove'><\/span> ","2015-04-01 04:11:12","<a href=\"http:\/\/localhost:8000\/admin\/event\/20\/edit\" class=\"btn btn-success btn-sm iframe\" ><span class=\"glyphicon glyphicon-pencil\"><\/span>  Edit<\/a>\n                    <a href=\"http:\/\/localhost:8000\/admin\/event\/20\/delete\" class=\"btn btn-sm btn-danger iframe\"><span class=\"glyphicon glyphicon-trash\"><\/span> Delete<\/a>\n                    <input type=\"hidden\" name=\"row\" value=\"20\" id=\"row\">"],["2abe","2015-04-01 (Wed)"," monthly "," <span class=\"glyphicon glyphicon-ok\"><\/span> ","2015-04-01 03:46:16","<a href=\"http:\/\/localhost:8000\/admin\/event\/16\/edit\" class=\"btn btn-success btn-sm iframe\" ><span class=\"glyphicon glyphicon-pencil\"><\/span>  Edit<\/a>\n                    <a href=\"http:\/\/localhost:8000\/admin\/event\/16\/delete\" class=\"btn btn-sm btn-danger iframe\"><span class=\"glyphicon glyphicon-trash\"><\/span> Delete<\/a>\n                    <input type=\"hidden\" name=\"row\" value=\"16\" id=\"row\">"],["1abe","2015-04-01 (Wed)"," off "," <span class=\"glyphicon glyphicon-ok\"><\/span> ","2015-04-01 03:46:04","<a href=\"http:\/\/localhost:8000\/admin\/event\/15\/edit\" class=\"btn btn-success btn-sm iframe\" ><span class=\"glyphicon glyphicon-pencil\"><\/span>  Edit<\/a>\n                    <a href=\"http:\/\/localhost:8000\/admin\/event\/15\/delete\" class=\"btn btn-sm btn-danger iframe\"><span class=\"glyphicon glyphicon-trash\"><\/span> Delete<\/a>\n                    <input type=\"hidden\" name=\"row\" value=\"15\" id=\"row\">"]],"sColumns":["events.id","events.title","events.date","events.recurring","events.highlight","events.created_at","actions"],"aQueries":[]}  

As you can see, the id column is still included in the sColumns part:

    "sColumns":["events.id","events.title","events.date","events.recurring","events.highlight","events.created_at","actions"]

If I try to do what illuminate3 said, and add this part to the view

    "columns": [
        {data: 'id', name: 'events.id', visible: false}
    ],

Then I'll get this error

    DataTables warning: table id=table - Requested unknown parameter 'id' for row 0. For more information about this error, please see http://datatables.net/tn/4

I'm sorry if it's just me who aren't understanding this well enough

**Comment by illuminate3** [comment]
@Zalon 

I liked to issue #12 above.
It has lots of details and code examples.

I used "visible: false" in the js declaration which does not solve your problem (which I had too) but it does work.

**Comment by yajra** [comment]
Should be fixed on v4.0.12 for L5 and 3.3.15 for L4.
