### ISSUE TITLE
Eloquent issue

### ISSUE THREAD

**Issue by bart** [yajra/laravel-datatables-oracle#2]
First of all, your package is amazing simple. I have a questions so far:

I can't use an Eloquent model like this:
```
return Datatables::of(Project::with('owner'))->make();

// ErrorException in Datatables.php line 285: Invalid argument supplied for foreach()
```

I'm on Laravel 5, any idea?

Thanks and regards!

**Comment by yajra** [comment]
Hi,

You need to specify the selected fields like below.

```php
return Datatables::of(Project::with('owner')->select('id','name'))
->editColumn('name', function ($product)
{
	dd($product);
})
->make();
```

And if you're using DataTable 1.10, try using `->select('*')` then `->make(true)`.

**Comment by bart** [comment]
Awesome, thanks a lot!
