### ISSUE TITLE
Get all entries (lengthMenu)

### ISSUE THREAD

**Issue by bart** [yajra/laravel-datatables-oracle#20]
When using -1 in lengthMenu option (https://datatables.net/reference/option/lengthMenu) to show all entries the package only returns 10 results. Any solution for that or does it require some code changes? Maybe I missed something.

**Comment by yajra** [comment]
Thanks for reporting. This should be fixed now on v4.1.0 for L5 and v3.4.0 for L4.

**Comment by bart** [comment]
I think it shows all records now in 4.1.0, doesn't it?

**Comment by yajra** [comment]
@bart Yes, it seems that 4.1.0 have produces an error as reported on #21. Had posted a patch 4.1.1 and reverted empty to is_null. Kindly check again and test. Thanks!

**Comment by bart** [comment]
@yajra It works well again in 4.1.4. Awesome! Thank you so much for quick bug fixing!
