### ISSUE TITLE
Paging broken after updating

### ISSUE THREAD

**Issue by timo002** [yajra/laravel-datatables-oracle#21]
I just updated to 4.1.0 to get column searching working. But now I loads all te results in the first page. Clicking on the 2nd page only loads the number of rows selected. Clicking on the first page again, all rows are loaded again. Looks like limit is not working.

The paging is working fine and also changes when I change the number of shown records per page.

**Comment by timo002** [comment]
I think I found the issue!

Datatables.php line 548:
```
if ( ! empty($this->input['start']) && ! empty($this->input['length']) && $this->input['length'] != -1) {
```
This validates if `input['start']` not is empty. But `0` is also empty. So the paging fails on the start of `0` (first page). I think this needs to be `isset`.

```
if ( isset($this->input['start']) && ! empty($this->input['length']) && $this->input['length'] != -1) {
```

**Comment by yajra** [comment]
Good catch! thanks for reporting. I reverted empty to is_null!
