### ISSUE TITLE
Problem when doing any kind of filtering

### ISSUE THREAD

**Issue by santigarcor** [yajra/laravel-datatables-oracle#22]
Hi yajra, first of all, your plugin is really amazing, but im having a problem with the last update that you did, in the version 4.0.11 i can make any kind of filter without problems, but i decided to update to 4.1.2.1 and when i try to filter something, laravel crashes and says :

`FatalErrorException in Datatables.php line 439:
Function name must be a string`

But when i try to do the filter by one specific column it says:

`ErrorException in Datatables.php line 473:
Undefined variable: connection`

Anyway thank you, meanwhile i'm using 4.0.11

**Comment by yajra** [comment]
thanks for reporting.. a copy paste issue error on my last commit. my bad sorry!

**Comment by yajra** [comment]
... still fixing please use 4.0.11 atm...

**Comment by yajra** [comment]
done.. kindly checkout v4.1.3.1... sorry for the inconvenience

**Comment by santigarcor** [comment]
Thank you friend, this package is amazing :+1:
