### ISSUE TITLE
Just a few words

### ISSUE THREAD

**Issue by paguemaou** [yajra/laravel-datatables-oracle#23]
Many thanks for your wonderfull packadge !

Just a few words about the doc : 
 * could you mention that your packadge IS NOT Oracle exclusive, but works also with MySQL and ???
 * other packadges (like Chumper) works with Datatables 1.9 only. Could you mention that your packadge works (very well !!) with Datatables 1.10
 * I just encounter a little problemn with ->make() in place of  ->make(true) with Datables 1.10. You use both of them in the doc but you doesn't explain the difference. I found it in the threads, but it would be easier.

Last, mention your packadge to Eric Barnes of Laravel-news !!! ( Twitter at @ericlbarnes.)

Paguemaou

**Comment by yajra** [comment]
Thank you for the suggestions. I have updated the docs and hopefully it will make more sense. If you have more suggestions for improvements, I am open on accepting a PR. Thanks a lot!

**Comment by paguemaou** [comment]
Thanks for your reply and the readme commit. 

It will be easier for dummies like me !

**Comment by paguemaou** [comment]
Could you mention that you uses the "server side" and Ajax option of Datatables. So, your package works perfectly well with "big" tables ... and small ones !

**Comment by yajra** [comment]
Done and added with links to Datatables docs.

**Comment by illuminate3** [comment]
I said something similar before but I also suggest changing the name to something like "yajra tables" and remove "oracle" from the title.

When I first found your package, I thought this was an oracle only option but I still tried anyways just in case. I'm very glad I did because I am grateful for your package!

Salamat!

**Comment by yajra** [comment]
Will try to rename the package but it might break the installations of old users when doing a `composer update`. Will have to check how to rename the package without affecting old installations.

**Comment by illuminate3** [comment]
I don't think you can do that.

Maybe a new repository and just put a note in this one?

**Comment by rossedman** [comment]
:+1:

**Comment by sergiubologa** [comment]
Hi @yajra 

I installed your package and I have a problem. I try to use your implementation with data coming from Parse.com API, because that's where my app stores the data. As I saw it only supports Eloquent and Fluent Query Builder. Is there a way to make the of() method work if I pass as a parameter  an array that contains the data I need to display? I also posted a question on Stackoverflow regarding this: http://stackoverflow.com/questions/30000555/datatables-package-for-laravel-5-with-parse-as-data-source

Thanks in advance.

**Comment by yajra** [comment]
Hi @sergiubologa 

Your case is not currently possible with the package. I think [Chumper](https://github.com/Chumper/Datatable) will be able to accommodate your case. However, i think it's not Laravel 5 ready yet? Haven't used it personally.

On the other hand, I think I will add this feature having a datatables response using `Collection` in a future release.

**Comment by yajra** [comment]
Maybe, a workaround to do this using the package is by saving the data from Parse.com into a temporary table then then use a Builder like below:

```php

DB::table('temp')->delete();
TempModel::insert($parse_data);

$data = TempModel::select(['columns']);

return Datatables::of($data)->make(true);

```

**Comment by sergiubologa** [comment]
Thank you yajra for your response. Your workaround with a temp table and Builder would work, but I have multiple datatables to display in my application and it would turn into a total mess. :)

Anyway, I'll probably end up writing my own class to handle this case.

**Comment by yajra** [comment]
@sergiubologa FYI: i just created issue #36 which plans to add support for a Collection as data source for Datatables. If you have some spare time, kindly checkout and test develop branch. Thanks!

**Comment by sergiubologa** [comment]
Great. Thank you. Hope to find some time for it.

**Comment by yajra** [comment]
FYI: Here is a [demo app](https://github.com/yajra/laravel-datatables-demo) for Datatables with Collection. 

@illuminate3 beta testers are welcome ^_^. Thanks!

BTW: closing this thread and lets continue the discussion on #36
