### ISSUE TITLE
Question : individual column searching (select input)

### ISSUE THREAD

**Issue by paguemaou** [yajra/laravel-datatables-oracle#25]
I'd like to use your package with  *serverside* data for doing something like this : 

http://www.datatables.net/examples/api/multi_filter_select.html

I'm new to Datatables (and JS !!!). I've tested the example, but it works "client side".

Do you thinks it's possible (and easy) to transform it in serverside ? 
Does somebody code things like this ?

Regards,
Paguemaou

**Comment by yajra** [comment]
I just tried this and the package works with column search. However, the search result is not 100% accurate especially when the value have special chars. I also made some adjustment on the demo js for it to work.

```js
initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                        column
                            .search( val ? val : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
```

Will tag this as for enhancement. And will fine tune the search result next week.
