### ISSUE TITLE
How to add checkmark at left side of the table?

### ISSUE THREAD

**Issue by andikaamri** [yajra/laravel-datatables-oracle#26]
Hello Yajra,

How can I add checkmark at left side of the table for all the table (means editing the table template)?

Thanks!

**Comment by yajra** [comment]
Hi,

Do you mean a checkbox on the table? One way you can achieve this is via the js script:

```php
"columns": [
	{ "data": function(data){
	   return '<input type="checkbox" name="id[]" value="'+ data.id +'" />';
	}, "orderable": false, "searchable":false, "name":"id" }
]
```

Another way is to add this on your server side script: just a trick via `editColumn`:
```php
$users = User::select(['id as checkmark', 'id', 'name'])
return Datatables::of($users)
	->editColumn('checkmark', function($user) {
		return '<input type="checkbox" value='. $user->id .'>';
	})
	->make(true);
```

and on your view:
```js
'columns': [
	{ 'data': 'checkmark' 'orderable': false, 'searchable':false, 'name':'id' }
]
```

**Comment by shubhamnegi987** [comment]
hey yajra when i use this 
"columns": [
    { "data": function(data){
       return '<input type="checkbox" name="id[]" value="'+ data.id +'" />';
    }, "orderable": false, "searchable":false, "name":"id" },
{ data: 'action', name: 'action', orderable: false, searchable: false},
]
it show chekcbox but after checkbox it show value which is id so how to fix it
