### ISSUE TITLE
Not able to get the search working

### ISSUE THREAD

**Issue by mahowebdesign** [yajra/laravel-datatables-oracle#27]
yajra, really like the package. Only i cannot get the search to work. I want to search on model name, wich i got trough a join. Is this possible?

Everything works fine, the ID's get converted into model names in the table. But when i want to search i on a model name, i get an error:

` SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous (SQL: select count(*) as aggregate from (select '1' as row_count from `part` left join `model` on `model`.`model_id` = `part`.`model_id` where (LOWER(`name`) LIKE %fzr%)) count_row_table) `

My code:

` $parts = Part::select('part.part_id', 'model.name')
			->leftJoin('model', 'model.model_id','=','part.model_id'); `

JS:

` oTable = $('#table').DataTable({ `
`    "processing": true,`
`    "serverSide": true,`
`    "ajax": "{{ URL::route('part.datatables') }}",`
`    "columns": [`
`        {data:  'part_id', "orderable": false, "searchable":false, name: 'part_id'},`
`        {data: 'name', "orderable": false, "searchable":true, name: 'name'}`
`    ]`
`}); `

I"m not sure if i`m making an mistake, or that its just not possible.

**Comment by mahowebdesign** [comment]
Can be closed:

Fix it by doing:

` $parts = Part::with('model'); `
and
` {data: 'model.name', "orderable": true, "searchable":true, name: 'name'} `

Now, model name can be searched. Great! Really nice this, thanks yajra

**Comment by fabioi** [comment]
+1

**Comment by fabioi** [comment]
- In order to avoid ambiguous field definitions, it is possible to specify the columns like below:
{data: 'name', name: 'users.name'},     //note the dot notation on the name attribute

- To hide a column from searching I did the following (but maybe there is a cleaner way)
{data: 'actions', name: ''},

Hope it helps

**Comment by mahowebdesign** [comment]
Hm, that doens't work for me. I use: ` data: 'users.name', name: 'users' `   , and that did the trick for avoiding ambiguous field definitions.

The problem i have now, is that the search giving me random results. So sometimes i get the correct 'type.name' back, and sometimes it don't. Only the first column gets perfectly searched (id's).

**Comment by fabioi** [comment]
I am sorry that does not work for you.  Below the  code I am using at the moment in order to play with the plugin:

```php
$users = User::leftjoin('role_user', 'role_user.user_id', '=', 'users.id')
			->leftjoin('roles',
				'roles.id',
				'=',
				'role_user.role_id')
			->join('user_profiles',
				'user_profiles.id',
				'=',
				'users.id'
			)
			->select(array(
				'user_profiles.name',
				'user_profiles.surname',
				'users.id',
				'users.email',
				'users.confirmed',
				'roles.name as rolename',
				'users.created_at'
			));


		return Datatables::of($users)
			->removeColumn('id')
			->make(true);
```
The table
```HTML
 <table id="users" class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th class="col-md-3">{{{ Lang::get('users/table.name') }}}</th>
                            <th class="col-md-3">{{{ Lang::get('users/table.surname') }}}</th>
                            <th class="col-md-3">{{{ Lang::get('users/table.email') }}}</th>
                            <th class="col-md-3">{{{ Lang::get('users/table.confirmed') }}}</th>
                            <th class="col-md-3">{{{ Lang::get('users/table.role') }}}</th>
                            <th class="col-md-3">{{{ Lang::get('users/table.created_at') }}}</th>
                          

                        </tr>
                        </thead>
                    </table>
```

The JS
```javascript
 <script type="text/javascript">
        $(document).ready(function () {
            oTable = $('#users').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "api",
                "columns": [
                    {data: 'name',  name: 'user_profiles.name'},
                    {data: 'surname', name: 'surname'},
                    {data: 'email', name: 'email'},
                    {data: 'confirmed', name: 'confirmed'},
                    {data: 'rolename', name: 'roles.name'},
                    {data: 'created_at', name: 'users.created_at'}
                  
                ]
            });
        });
    </script>

```

**Comment by fabioi** [comment]
I am using it with the the most recent version of datatables js plugin

**Comment by mahowebdesign** [comment]
Hm, i rewrote my code, with your example next to it. And now it's working! Cannot really point out where i made a mistake. Thanks!

**Comment by fabioi** [comment]
I am very happy that it helped :-)!! I think we can close the topic

**Comment by yajra** [comment]
@mahowebdesign for clarification the issue was due to `name` field does exists on both tables and as @fabioi example, you should add the table prefix (`model.name`) on your js to fix it. The reason is using `->make(true)` will use the field names defined on your js for better flexibility. (The old approach uses the fields on your select statement and will heavily rely on it's arrangement)

```js
{data: 'model.name', "orderable": false, "searchable":true, name: 'model.name'},
```

**Comment by herohat** [comment]
Just one tip more.

If you are using Datatables as a services implementation,  so the columns going like this:

`['name' => 'model.name', 'data' => 'name', 'title' => 'My name title', 'orderable' => true, 'searchable' => true],`

example:

`    /**
     * Get columns.
     *
     * @return array
     */
    private function getColumns()
    {
        return [
            ['name' => 'subscripciones.id', 'data' => 'id', 'title' => 'ID', 'orderable' => true, 'searchable' => false],
            ['name' => 'eventos.nombre', 'data' => 'evento_nombre', 'title' => 'Evento', 'orderable' => true, 'searchable' => true],
            'nombres',
            'apellidos',
            'email',
            'identificacion',
            'tiempo_estimado',
            'tiempo',
            ['name' => 'subscripciones.created_at', 'data' => 'created_at', 'title' => 'Creación', 'orderable' => true, 'searchable' => true],
            ['name' => 'resultados.updated_at', 'data' => 'updated_at', 'title' => 'Actualizado', 'orderable' => true, 'searchable' => true],
        ];
    }`
