### ISSUE TITLE
Quick search not working

### ISSUE THREAD

**Issue by bart** [yajra/laravel-datatables-oracle#29]
Hey there,

I'm using the latest version of the package (4.2.0) but don't get quick search working. When I use client-side processing everything works fine. But when using server-side processing the table does not update.

My server-side processing looks like this:

```php
$profiles = Customer::leftJoin('presets','presets.id','=','customers.support_status_id')
->leftJoin('partners','partners.id','=','customers.partner_id')
->select(['customers.reference_number', 'customers.name as name1', 'customers.postcode', 'customers.city', 'presets.value', 'partners.name as name2', 'customers.id']);

return Datatables::of($profiles)->make();
```

Any idea what could cause the issue?

Thanks a lot!

**Comment by yajra** [comment]
Can you paste your js declaration? I suggest using the script pattern like below. Also, can you please paste any error that occurs using developer tools inspector/firebug?

```js
<script type="text/javascript">
$(document).ready(function() {
    oTable = $('#users').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "/users/data",
        "columns": [
            {data: 'username', name: 'username'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'actions', name: 'actions'}
        ]
    });
});
</script>
```

**Comment by bart** [comment]
Hey @yajra, thanks fror your response.

My JS looks like this:

```
$('.dt').dataTable({
        "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
        "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
            $(nRow).data("link", link + "/" + aData[idIndex]);
        },
        "language": {
            "url": "/libs/js/german.json"
        },
        "processing": true,
        "serverSide": true,
        "ajax": "/datatables/customers"
    }).on('click', 'tbody tr', function(e) {
        location.href = $(this).data('link');
    });
```

Chrome debug console does not contain any error or our output. When doing the same using client-side processing it works fine.

**Comment by yajra** [comment]
I was able to replicate the issue now. Search will not work if `columns` are not declared on your js because the new version uses it as reference to search for the fields. As a work around for now, kindly add the columns on your javascript like until we released a new patch for this.

```js
"columns": [
            {data: 'username', name: 'users.username'},
            {data: 'email', name: 'users.email'},
            {data: 'created_at', name: 'users.created_at'},
            {data: 'actions', name: 'actions', 'searchable':false}
        ]
```

**Comment by yajra** [comment]
Should be fixed on v4.2.1. Kindly checkout and verify. thanks!

**Comment by bart** [comment]
Amazing! It's working now in 4.3.0. Thank you so much @yajra

**Comment by yasherarafath** [comment]
sorting in case sensitive how i controll these things in code?

**Comment by webwizard02** [comment]
Hi @yasherarafath 
just refer your answer here. https://github.com/yajra/laravel-datatables/issues/44

Credits for the Owner
