### ISSUE TITLE
How to add Print button?

### ISSUE THREAD

**Issue by infoshahin** [yajra/laravel-datatables-oracle#30]
This is my Js:

 oTable = $('#projects').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{{ URL::to('/projectsdata') }}",
        "columns": [
            {data: 'project_name', name: 'project_name'},
            {data: 'project_location', name: 'project_location'},
            {data: 'start_date', name: 'start_date'},
            {data: 'end_date', name: 'end_date'},
            {data: 'id', name: 'id'}
        ]
    });

 How can I add print Button in this?

**Comment by yajra** [comment]
Do you mean a print button for every row? You can check issue #26 and follow my suggestions there. Thanks!

**Comment by infoshahin** [comment]
No No! That question is How to add checkmark at left side of the table?  , Actually I want to add a print button on datatable. Like as 

"oTableTools": {
            "aButtons": [
                "copy",
                "print",
                {
                    "sExtends":    "collection",
                    "sButtonText": "Save",
                    "aButtons":    [ "csv", "xls", "pdf" ]
                }
            ]
        }


When I add this code in "laravel-datatables-oracle" it not works.

**Comment by yajra** [comment]
oic, you're referring on table tools. Then this is not part of the package scope but on `DataTables` plugin itself. See this for details https://www.datatables.net/extensions/tabletools/

**Comment by infoshahin** [comment]
Ok

**Comment by yajra** [comment]
@infoshahin, I just pre-released a  a v6.0.0-alpha version which supports server-side buttons. It would be appreciated in you can join as alpha tester since I think it's your requirement too? Feedbacks are also appreciated. ^_^ Thanks!
