### ISSUE TITLE
How can I use if else in select query?

### ISSUE THREAD

**Issue by infoshahin** [yajra/laravel-datatables-oracle#32]
I want to When employees.type == "Office" then Join Office table, and When employees.type == "Project"  then Join Project table, Is it possible for every table row check this condition?

My query is like that.. 

$employeetbl = Employee::Join('projects','employees.type_id','=','projects.id')                    ->select(array('employees.name','employees.type','projects.project_name','employees.join_date','employees.comment','employees.id AS eid'));
         return Datatables::of($employeetbl)
	    ->make();

**Comment by yajra** [comment]
I think it's not possible to conditionally join a table. However, I think you can utilize the Polymorphic Relationship of Laravel to accomplish your task. But you need to use the object data source `->make(true)` to be able to access those properties and display it on your results. The downside to this approach is that you will not be able to search and sort on those polymorphic fields.

**Comment by infoshahin** [comment]
Ok, I got your point. Tnq.
