### ISSUE TITLE
i can't use addColumn in datatables(l5)

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables-oracle#33]
when use addColumn ,the datatable has somethings wrong 
js datatables setting: "bServerSide": true(datatables 1.9.4)
php error see images
![20150429174402](https://cloud.githubusercontent.com/assets/9793122/7388525/83d96e8a-ee98-11e4-8f8e-8f71833048a9.png)
![20150429174413](https://cloud.githubusercontent.com/assets/9793122/7388526/83de975c-ee98-11e4-8911-1c9229735cba.png)

if  "bServerSide": false, Pagination just has one page ,how to do?
![20150429174451](https://cloud.githubusercontent.com/assets/9793122/7388560/c748b4be-ee98-11e4-94b0-ada286779eed.png)

And use datatables 1.10.5.the  problem still exists

see here

if i don‘t add html  class addClass, datatables hasn't problem ,return json has addColumn "222", when add html class"<th>addColumn</th>" an refresh web, the datatables has error

![20150429182021](https://cloud.githubusercontent.com/assets/9793122/7389114/8a31ef78-ee9d-11e4-9565-b67daecd4b1e.png)
![20150429182008](https://cloud.githubusercontent.com/assets/9793122/7389118/90dcec4c-ee9d-11e4-9ea9-1e6c9dc282ec.png)
![20150429181927](https://cloud.githubusercontent.com/assets/9793122/7389127/9a36ba16-ee9d-11e4-8c2b-763089b0d08d.png)

**Comment by yajra** [comment]
can you please paste your javascript side? 

For DT1.10++ you need to set the `addColumn` part as `searchable:false, orderable:false` to prevent this issue.

For DT1.9++, will have to check it as it maybe a bug. I suggest that you stick/use version 1.10++

**Comment by openvast** [comment]
javascript 

![20150429232351](https://cloud.githubusercontent.com/assets/9793122/7394553/ece88e14-eec6-11e4-90de-7c32d252a0f7.png)
![20150429232125](https://cloud.githubusercontent.com/assets/9793122/7394557/f354e2f2-eec6-11e4-8d7f-d08f3c962a0d.png)

use DT1.94 longtime , change to use dt1.10+ ,i must revise the html css and rebuilt a DT  Pagination like that。AND I be not good at javascript ,^.^^.^^.^  help

**Comment by openvast** [comment]
HI, I try to solve this problem, and success。

**Comment by openvast** [comment]
HI, I try to solve this problem, and success。
![20150430000803](https://cloud.githubusercontent.com/assets/9793122/7395599/7e38bd02-eecd-11e4-975d-6dc098dd3567.png)
in image line 961 ,define a new column in array ....

can you use that and update the project as soon as fast to solve the problem forever.
English is not good,Thank you for your patience to read^.^^.^.^^.^
