### ISSUE TITLE
give an Example for view

### ISSUE THREAD

**Issue by vijaysebastian** [yajra/laravel-datatables-oracle#4]
i am using this plugin. i got the json value. how it will show in my website

**Comment by yajra** [comment]
Your should look something like this:

```php
<table id="users" class="table table-hover table-condensed">
	<thead>
		<tr>
			<th class="col-md-3">{{{ Lang::get('admin/users/table.username') }}}</th>
			<th class="col-md-3">{{{ Lang::get('admin/users/table.email') }}}</th>
			<th class="col-md-3">{{{ Lang::get('admin/users/table.created_at') }}}</th>
			<th class="col-md-3">{{{ Lang::get('table.actions') }}}</th>
		</tr>
	</thead>
	<tfoot>
		<tr >
			<td colspan="4"></td>
		</tr>
	</tfoot>
</table>

<script type="text/javascript">
$(document).ready(function() {
	oTable = $('#users').DataTable({
		"processing": true,
		"serverSide": true,
		"ajax": "{{ url('/users/datatable') }}",
		"columns": [
			{data: 'username', name: 'username'},
			{data: 'email', name: 'email'},
			{data: 'created_at', name: 'created_at'},
			{data: 'actions', name: 'actions'}
		]
	});
});
</script>
```

**Comment by vijaysebastian** [comment]
thanks.. but so far i could not figure out my problem.

**Comment by vijaysebastian** [comment]
//route
get('list','peopleController@getDatatable');
get('postlist','peopleController@table');

//controller

public function getDatatable()
    {
     
    $song = $this->song->get();
    return View::make('people.index',compact('song'));
       
    }
    public function table()
    {
    	$song = $this->song->select('title');

    return Datatables::of($song)->make(true);
    }


//index.blade.php

<table id="users" class="table table-hover">
    <thead>
        <tr>
            <th class="col-md-3">id</th>
            <th class="col-md-3">title</th>
            
        </tr>
    </thead>
</table>

<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">

$(document).ready(function() {
    oTable = $('#users').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "localhost/laravel5/laravel-master/public/postlist",
        "columns": [
            {data: 'id', name: 'id'},
            {data: 'title', name: 'title'}
            
        ]

    });
});

</script>

**Comment by vijaysebastian** [comment]
my json value:

{"sEcho":0,"iTotalRecords":3,"iTotalDisplayRecords":3,"aaData":[{"title":"fall"},{"title":"Be Alright"},{"title":"song"}],"sColumns":["title"],"aQueries":[]}

**Comment by yajra** [comment]
I think your using Datatables 1.9 and below. I suggest you use version 1.10++ for more flexibility.

But if you want to use the lower version, you should use the server response like below: 

```php
public function table()
{
    $song = $this->song->select('title');

return Datatables::of($song)->make();
}
```

Note: I removed the `true` parameter on make function.

**Comment by yajra** [comment]
added on read me.
