### ISSUE TITLE
adding columns before ones generated by "of(...)"

### ISSUE THREAD

**Issue by tmihetec** [yajra/laravel-datatables-oracle#6]
hi how can i add columns before columns generated by "of(...)" method?
i wold like to hav first 2 columns for "action", then columns from database.

br and sorry if question is lame :) 
tom

**Comment by yajra** [comment]
I suggest you use Datatables 1.10++ and that way you can arrange the columns the way you want it regardless of server response arrangement. Check the example view I provided [here](https://github.com/yajra/laravel-datatables-oracle/issues/4).

On the other hand, it's not possible if your using Datatables 1.9 and below.
