### ISSUE TITLE
Possible errors in the code

### ISSUE THREAD

**Issue by spajz** [yajra/laravel-datatables-oracle#9]
Hi,
I tried this package with Laravel 5 and DT 1.10. Works well, but I think there is a error in 2 places in Datatables class:
```
$copy_this->wildcardLikeString(....
```
I assume that this should be
```
$this->wildcardLikeString(....
```
or we need variable
```
$copy_this = $this;
```
Thanks

**Comment by yajra** [comment]
thanks for the advise.
